'use strict';

// Lockstep guard for migration 030 (conversation_events.seq + the index swap).
//
// Same machinery and the same two-path shape as conversationEvents.test.js and
// conversationsOriginChannel.test.js: real runner, throwaway scratch DATABASES
// on the DATABASE_URL server, dropped in a finally, suite skipped when
// DATABASE_URL is unset.
//
// ── Why this exists ALONGSIDE the 029 guard, and is not folded into it ───────
// The two fabricate different pre-states and therefore prove different halves.
//
//   conversationEvents.test.js  DROPs the whole table and replays the CHAIN
//                               (029 then 030). That proves GENESIS: a fresh
//                               database built from schema.sql matches what
//                               replaying every migration for this table
//                               produces. Issue 20's first production deploy
//                               is exactly that path.
//
//   this file                   DROPs only 030's own delta — the seq column
//                               and the swapped index — and runs 030 alone.
//                               That proves MIGRATE: a database already at 029
//                               (both of ours are, right now) advanced by this
//                               one file converges on the same shape.
//
// Folding them together would lose the second. A 030 that only worked when
// replayed from an empty table would pass a chain-replay guard and still be
// wrong for every existing database, which is the population that matters here
// — the local saas_crm_test and the remote Neon neondb are both at 029.
//
// ── Why this asserts the IDENTITY PROPERTY, not just "a column named seq" ────
// information_schema.columns.data_type would read `bigint` for a plain BIGINT
// column with no default, for a BIGSERIAL, and for GENERATED BY DEFAULT AS
// IDENTITY alike. All three would pass a columns-only comparison and none of
// them is what 030 ships. `is_identity`/`identity_generation` are the columns
// that tell those apart, and GENERATED ALWAYS is load-bearing: it is what stops
// a caller supplying a seq by hand and corrupting the order the migration
// exists to establish. So that is asserted directly, by attempting the insert
// and requiring it to be REFUSED.
//
// ── Why the INDEX assertion is on the definition, not the name ──────────────
// 030's index swap keeps the NAME idx_conversation_events_conversation and
// changes only the columns. A name-list comparison — which is all the 029 guard
// does before its deepEqual — cannot see that at all. Shipping seq while
// leaving the index on (conversation_id, created_at) is the trap named in the
// migration header: it makes the read strictly worse (bitmap scan of every
// event on the thread plus a top-N heapsort, against a one-row index scan) and
// nothing else in this suite asserts a query plan. So the definition is pinned.

require('dotenv').config();
const { describe, it, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { Client } = require('pg');

const runner = require('../../src/db/migrate');

const ADMIN = process.env.DATABASE_URL;
const REAL_MIGRATIONS = path.join(__dirname, '..', '..', 'src', 'db', 'migrations');
const MIG_030 = '030_conversation_events_seq.sql';

const SSL = process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false;
const SILENT = { log() {}, error() {} };

function swapDb(cs, name) { const u = new URL(cs); u.pathname = '/' + name; return u.toString(); }
function admin() { return new Client({ connectionString: ADMIN, ssl: SSL }); }

// Scratch-DB prefix — MUST be disjoint from every other file's prefix AND from
// every other file's sweep PATTERN. node --test runs files concurrently and a
// sweep that matched this prefix could drop this suite's database mid-genesis.
// Two sweeps in the repo use LIKE with UNESCAPED '_', which is a single-char
// wildcard: 'zyon_ce_%' (conversationEvents.test.js) needs 'ce' at offsets 5-6,
// and 'zyon_test_conv_%' (admin/conversations.test.js) needs 't' at offset 5.
// 'zyon_cs_' satisfies neither. This file's own sweep escapes properly.
const SCRATCH_PREFIX = 'zyon_cs_';

async function dropDb(name) {
  const c = admin();
  await c.connect();
  try {
    await c.query('SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname=$1 AND pid<>pg_backend_pid()', [name]);
    await c.query('DROP DATABASE IF EXISTS ' + name);
  } finally { await c.end(); }
}

async function withScratch(fn) {
  const name = SCRATCH_PREFIX + crypto.randomBytes(6).toString('hex');
  const c = admin();
  await c.connect();
  await c.query('CREATE DATABASE ' + name);
  await c.end();
  try {
    return await fn({ name, cs: swapDb(ADMIN, name) });
  } finally {
    await dropDb(name);
  }
}

async function exec(cs, sql, params) {
  const c = new Client({ connectionString: cs, ssl: SSL });
  await c.connect();
  try { return await c.query(sql, params); } finally { await c.end(); }
}

// Full shape of a table, INCLUDING the identity columns — ordinal-independent,
// so `seq` arriving last on the migrate path and wherever schema.sql declares
// it on the genesis path is not read as drift.
async function shapeOf(cs, table) {
  const r = await exec(cs, `
    SELECT column_name, data_type, is_nullable, column_default,
           is_identity, identity_generation
      FROM information_schema.columns
     WHERE table_name = $1
     ORDER BY column_name`, [table]);
  return r.rows;
}

async function indexesOf(cs, table) {
  const r = await exec(cs, `
    SELECT indexname, indexdef FROM pg_indexes
     WHERE tablename = $1 ORDER BY indexname`, [table]);
  return r.rows;
}

async function fksOf(cs, table) {
  const r = await exec(cs, `
    SELECT kcu.column_name, ccu.table_name AS refs, rc.delete_rule
      FROM information_schema.table_constraints tc
      JOIN information_schema.key_column_usage kcu
        ON kcu.constraint_name = tc.constraint_name
      JOIN information_schema.constraint_column_usage ccu
        ON ccu.constraint_name = tc.constraint_name
      JOIN information_schema.referential_constraints rc
        ON rc.constraint_name = tc.constraint_name
     WHERE tc.table_name = $1 AND tc.constraint_type = 'FOREIGN KEY'
     ORDER BY kcu.column_name`, [table]);
  return r.rows;
}

async function checksOf(cs, table) {
  const r = await exec(cs, `
    SELECT pg_get_constraintdef(con.oid) AS def
      FROM pg_constraint con
      JOIN pg_class rel ON rel.oid = con.conrelid
     WHERE rel.relname = $1 AND con.contype = 'c'
     ORDER BY pg_get_constraintdef(con.oid)`, [table]);
  return r.rows;
}

async function sweep() {
  const c = admin();
  await c.connect();
  try {
    const { rows } = await c.query("SELECT datname FROM pg_database WHERE datname LIKE 'zyon\\_cs\\_%'");
    for (const r of rows) {
      await c.query('SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname=$1 AND pid<>pg_backend_pid()', [r.datname]);
      await c.query('DROP DATABASE IF EXISTS ' + r.datname);
    }
  } finally { await c.end(); }
}

describe('conversation_events.seq (migration 030)', { skip: ADMIN ? false : 'DATABASE_URL not set' }, () => {
  before(sweep);
  after(sweep);

  it('schema.sql and the real 030 file converge on the same columns, indexes, FKs and checks', async () => {
    await withScratch(async ({ cs }) => {
      // ── Path A: genesis from schema.sql ──────────────────────────────
      const g = await runner.genesis({ connectionString: cs, logger: SILENT });
      assert.equal(g.ok, true, 'genesis succeeded');

      const s = await runner.status({ connectionString: cs, logger: SILENT });
      assert.equal(s.hasPending, false, 'zero pending after genesis');
      const row = s.applied.find((a) => a.filename === MIG_030);
      assert.ok(row, '030 recorded');
      assert.equal(row.stamped, true, '030 stamped, not executed (genesis trusts schema.sql)');
      assert.equal(s.mismatches.length, 0, 'no checksum mismatches');

      const colsFromSchema = await shapeOf(cs, 'conversation_events');
      const seq = colsFromSchema.find((c) => c.column_name === 'seq');
      assert.ok(seq, 'schema.sql builds conversation_events.seq');

      // The mechanism, asserted rather than assumed. `data_type` alone cannot
      // tell BIGINT from BIGSERIAL from GENERATED BY DEFAULT.
      assert.equal(seq.data_type, 'bigint');
      assert.equal(seq.is_nullable, 'NO', 'an identity column is implicitly NOT NULL');
      assert.equal(seq.is_identity, 'YES', 'an IDENTITY column, not a BIGSERIAL and not a plain BIGINT');
      assert.equal(seq.identity_generation, 'ALWAYS',
        'GENERATED ALWAYS, not BY DEFAULT — nothing may supply a seq by hand');

      // created_at is UNCHANGED. 030 rejected clock_timestamp(); if a future
      // session reaches for it, this line is the one it has to delete.
      const createdAt = colsFromSchema.find((c) => c.column_name === 'created_at');
      assert.match(createdAt.column_default, /now\(\)/i,
        'created_at stays transaction time, as every other timestamp in this schema is');

      const idxFromSchema = await indexesOf(cs, 'conversation_events');
      assert.deepEqual(
        idxFromSchema.map((i) => i.indexname),
        ['conversation_events_pkey',
         'idx_conversation_events_conversation',
         'idx_conversation_events_tenant_type_created'],
        '030 swaps an index in place — the NAMES are unchanged, which is exactly why the definitions below are pinned'
      );
      const convIdx = idxFromSchema.find((i) => i.indexname === 'idx_conversation_events_conversation');
      assert.match(convIdx.indexdef, /\(conversation_id, seq DESC\)/,
        'the per-thread index orders by seq — leaving it on created_at is the trap in 030\'s header: strictly worse, and silent');
      const tenantIdx = idxFromSchema.find((i) => i.indexname === 'idx_conversation_events_tenant_type_created');
      assert.match(tenantIdx.indexdef, /\(tenant_id, type, created_at DESC\)/,
        '030 leaves the tenant/type index alone — a different axis, on wall-clock time');

      const fksFromSchema = await fksOf(cs, 'conversation_events');
      const checksFromSchema = await checksOf(cs, 'conversation_events');
      assert.equal(checksFromSchema.length, 1, '030 adds no CHECK; `actor` is still the only one');

      // ── GENERATED ALWAYS, proved by refusal ──────────────────────────
      // Rejected during query rewrite (SQLSTATE 428C9), before execution, so
      // this needs no tenant/customer/conversation rows to be meaningful.
      await assert.rejects(
        () => exec(cs, `INSERT INTO conversation_events
                          (tenant_id, conversation_id, customer_id, type, channel, actor, seq)
                        VALUES (gen_random_uuid(), gen_random_uuid(), gen_random_uuid(),
                                'handled', 'whatsapp', 'ai', 1)`),
        (err) => {
          assert.equal(err.code, '428C9',
            'cannot insert a non-DEFAULT value into an identity column — got ' + err.code);
          return true;
        },
        'a caller supplying seq by hand must be REFUSED, not silently honoured'
      );

      // ── Path B: fabricate pre-030, then run the REAL migration file ──
      // Only 030's own delta is unwound: the column and the index swap. This is
      // the state both live databases are actually in.
      // NOTE: dropping the column takes the index WITH it — the index is on
      // (conversation_id, seq DESC), so it depends on seq and Postgres removes
      // it silently. There is no explicit DROP INDEX here for that reason, and
      // the assertion below pins the dependency rather than assuming it.
      await exec(cs, 'ALTER TABLE conversation_events DROP COLUMN seq');
      const orphaned = await indexesOf(cs, 'conversation_events');
      assert.ok(!orphaned.some((i) => i.indexname === 'idx_conversation_events_conversation'),
        'dropping seq drops the index that orders by it — no explicit DROP INDEX needed to fabricate pre-030');
      await exec(cs, 'CREATE INDEX idx_conversation_events_conversation ON conversation_events(conversation_id, created_at)');

      const pre = await shapeOf(cs, 'conversation_events');
      assert.ok(!pre.some((c) => c.column_name === 'seq'), 'pre-030 state fabricated: no seq');
      const preIdx = await indexesOf(cs, 'conversation_events');
      assert.match(
        preIdx.find((i) => i.indexname === 'idx_conversation_events_conversation').indexdef,
        /\(conversation_id, created_at\)/, 'pre-030 state fabricated: the old index');

      const sql = fs.readFileSync(path.join(REAL_MIGRATIONS, MIG_030), 'utf8');
      await exec(cs, sql);

      // ── The lockstep assertions: all four shapes, both paths ─────────
      assert.deepEqual(await shapeOf(cs, 'conversation_events'), colsFromSchema,
        'the real 030 file reproduces schema.sql\'s COLUMNS, identity property included — lockstep');
      assert.deepEqual(await indexesOf(cs, 'conversation_events'), idxFromSchema,
        'the real 030 file reproduces schema.sql\'s INDEXES — lockstep');
      assert.deepEqual(await fksOf(cs, 'conversation_events'), fksFromSchema,
        'the real 030 file leaves the FOREIGN KEYS untouched — lockstep');
      assert.deepEqual(await checksOf(cs, 'conversation_events'), checksFromSchema,
        'the real 030 file leaves the CHECK constraints untouched — lockstep');
    });
  });
});
