// Build-time only. Pulls the Telugu + Devanagari woff2 subsets of the Noto Sans
// families from Google Fonts and self-hosts them under public/demo/fonts/ so the
// DEMO-01 proof surface renders OFFLINE (clinic wifi, network disconnected).
// NOT shipped runtime code — run once, commit the resulting woff2 + fonts.css.
'use strict';

const fs = require('fs');
const path = require('path');

const OUT_DIR = path.join(__dirname, '..', '..', 'public', 'demo', 'fonts');
// A modern Chrome UA makes Google Fonts serve woff2 (vs ttf for old UAs).
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

const FAMILIES = [
  { css: 'Noto+Sans+Telugu:wght@400;600;700', subset: 'telugu', file: 'noto-telugu' },
  { css: 'Noto+Sans+Devanagari:wght@400;600;700', subset: 'devanagari', file: 'noto-devanagari' },
];

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`GET ${url} → ${res.status}`);
  return res.text();
}

async function fetchBinary(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`GET ${url} → ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

// Google's CSS2 output is a run of `/* subset */\n@font-face { ... }` blocks.
// Parse each into { subset, weight, url, unicodeRange }.
function parseBlocks(css) {
  const blocks = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*{([^}]*)}/g;
  let m;
  while ((m = re.exec(css)) !== null) {
    const subset = m[1];
    const body = m[2];
    const weight = (body.match(/font-weight:\s*(\d+)/) || [])[1];
    const url = (body.match(/url\(([^)]+)\)/) || [])[1];
    const unicodeRange = (body.match(/unicode-range:\s*([^;]+);/) || [])[1];
    blocks.push({ subset, weight, url, unicodeRange });
  }
  return blocks;
}

async function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const faces = [];

  for (const fam of FAMILIES) {
    const css = await fetchText(
      `https://fonts.googleapis.com/css2?family=${fam.css}&display=swap`
    );
    const blocks = parseBlocks(css).filter((b) => b.subset === fam.subset);
    if (blocks.length === 0) throw new Error(`no ${fam.subset} blocks for ${fam.css}`);

    for (const b of blocks) {
      const family = fam.css.split(':')[0].replace(/\+/g, ' ');
      const fileName = `${fam.file}-${b.weight}.woff2`;
      const bin = await fetchBinary(b.url);
      fs.writeFileSync(path.join(OUT_DIR, fileName), bin);
      console.log(`  ${fileName}  ${(bin.length / 1024).toFixed(1)} KB  (${b.unicodeRange ? 'ranged' : 'no-range'})`);
      faces.push({ family, weight: b.weight, fileName, unicodeRange: b.unicodeRange });
    }
  }

  const cssOut = faces
    .map(
      (f) =>
        `@font-face {\n` +
        `  font-family: '${f.family}';\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${f.weight};\n` +
        `  font-display: swap;\n` +
        `  src: url('./${f.fileName}') format('woff2');\n` +
        (f.unicodeRange ? `  unicode-range: ${f.unicodeRange};\n` : '') +
        `}`
    )
    .join('\n');

  const header =
    '/* Self-hosted Noto Sans Telugu + Devanagari (Telugu/Devanagari subsets).\n' +
    ' * Generated by scripts/demo/fetch_fonts.js — DEMO-01 offline proof surface.\n' +
    ' * Do not edit by hand; re-run the script to regenerate. */\n';

  fs.writeFileSync(path.join(OUT_DIR, 'fonts.css'), header + cssOut + '\n');
  console.log(`\nWrote ${faces.length} @font-face rules → public/demo/fonts/fonts.css`);
}

main().catch((e) => {
  console.error('fetch_fonts failed:', e.message);
  process.exit(1);
});
