'use strict';

// V1c — `/internal/voice/call/start` returns the greeting the worker speaks on
// join, for the language resolved BEFORE the caller has said anything.
//
// Two things are under test and they fail differently:
//
//  1. THE TRANSPORT. `/call/start` used to return four fields and no greeting,
//     so voice-agent/agent.py's `session.say()` guard was permanently false and
//     the greeting reached callers only as a prompt instruction — generated by
//     Gemini inside an ordinary turn, which means the caller had to speak first
//     and wait a full STT → brain → Gemini → TTS cycle to be greeted.
//
//  2. THE LANGUAGE, which is where the real bug was. `customers.preferred_
//     language` holds what Sarvam STT emitted ('te-IN'), because agent.py:523-524
//     → delegate_turn → customerService.js:69-73 persists it verbatim. The config
//     document is keyed on bare codes ('te'). Selecting a greeting with the stored
//     value directly finds nothing and falls through pickLine's English fallback:
//     a Telugu clinic's returning Telugu caller greeted in English, with a WARN
//     nobody reads as a bug. `configLang` is the single boundary that fixes it;
//     the `te-IN → Telugu` test below is the evidence, and it goes red if
//     configLang is reduced to the identity.
//
// The consent line is a legal-floor line, so it is asserted by its exact
// configured text per language — never by shape, never by a substring that could
// match an approximation.
//
// Shared test database (the voiceTenantHydration pattern), fixture tenant block
// `…-01c0-…`, unused elsewhere.

require('dotenv').config();

const { describe, it, before, after, mock } = require('node:test');
const assert = require('node:assert/strict');
const express = require('express');

const db            = require('../../src/db/db');
const hmac          = require('../../src/utils/hmac');
const logger        = require('../../src/infra/logging/logger');
const configService = require('../../src/modules/config/configService');
const tenantService = require('../../src/modules/tenant/tenantService');

const SECRET = 'v1c-greeting-test-secret';

const T = {
  CLINIC:   '00000000-0000-01c0-0000-000000000001', // te default, consent ON
  ENDEF:    '00000000-0000-01c0-0000-000000000002', // en default, consent ON
  NOCONSENT:'00000000-0000-01c0-0000-000000000003', // te default, consent OFF
  NOCONFIG: '00000000-0000-01c0-0000-000000000004', // no tenant_configs row at all
};

// Distinct per language so an assertion can never pass on the wrong one, and
// distinct between greeting and consent so their ORDER is observable.
const GREET = {
  te: 'నమస్తే! స్మైల్ డెంటల్ కి స్వాగతం.',
  hi: 'नमस्ते! स्माइल डेंटल में आपका स्वागत है।',
  en: 'Hello! Welcome to Smile Dental.',
};
const CONSENT = {
  te: 'ఈ కాల్ నాణ్యత కోసం రికార్డ్ చేయబడవచ్చు.',
  hi: 'यह कॉल गुणवत्ता के लिए रिकॉर्ड की जा सकती है।',
  en: 'This call may be recorded for quality purposes.',
};

let server;
let baseUrl;

async function cleanup() {
  for (const tid of Object.values(T)) {
    await db.query('DELETE FROM call_sessions WHERE tenant_id = $1', [tid]);
    await db.query('DELETE FROM messages WHERE tenant_id = $1', [tid]);
    await db.query('DELETE FROM conversations WHERE tenant_id = $1', [tid]);
    await db.query('DELETE FROM channel_identifiers WHERE tenant_id = $1', [tid]);
    await db.query('DELETE FROM customers WHERE tenant_id = $1', [tid]);
    await db.query('DELETE FROM tenant_config_revisions WHERE tenant_id = $1', [tid]);
    await db.query('DELETE FROM tenant_configs WHERE tenant_id = $1', [tid]);
    await db.query('DELETE FROM tenants WHERE id = $1', [tid]);
  }
  tenantService.invalidateTenantCache();
  configService.invalidateConfigCache();
}

async function callStart(tenantId, callerId) {
  const raw = JSON.stringify({ tenant_id: tenantId, caller_id: callerId, channel: 'voice' });
  const res = await fetch(`${baseUrl}/internal/voice/call/start`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', 'x-internal-signature': hmac.sign(raw, SECRET) },
    body: raw,
  });
  return { status: res.status, json: await res.json() };
}

// Seed a returning caller whose stored preferred_language is exactly `stored` —
// including the values only the worker's namespace can produce, and the values
// only an unvalidated writer can produce.
async function seedCaller(tenantId, phone, stored) {
  await db.query(
    'INSERT INTO customers (tenant_id, phone, preferred_language) VALUES ($1, $2, $3)',
    [tenantId, phone, stored]
  );
}

describe('call/start greeting (V1c)', () => {
  before(async () => {
    process.env.VOICE_INTERNAL_SECRET = SECRET;
    await cleanup();

    for (const [key, id] of Object.entries(T)) {
      await db.query(
        `INSERT INTO tenants (id, business_name, ai_prompt, ai_enabled, active)
         VALUES ($1, $2, NULL, true, true)`,
        [id, `V1c ${key}`]
      );
    }

    // Written through the REAL writer: schema-validated, defaults merged. What
    // the route reads is what the only production write path can produce.
    const langBlock = (def) => ({
      languages: { supported: ['te', 'hi', 'en'], default: def },
      greeting: { ...GREET },
    });

    await configService.writeTenantConfig(T.CLINIC, {
      ...langBlock('te'),
      recording_consent: { enabled: true, line: { ...CONSENT } },
    }, 'cli');

    await configService.writeTenantConfig(T.ENDEF, {
      ...langBlock('en'),
      recording_consent: { enabled: true, line: { ...CONSENT } },
    }, 'cli');

    await configService.writeTenantConfig(T.NOCONSENT, {
      ...langBlock('te'),
      recording_consent: { enabled: false, line: { ...CONSENT } },
    }, 'cli');

    // T.NOCONFIG deliberately gets no config row.

    const app = express();
    app.use('/internal/voice', require('../../src/routes/internalVoice'));
    await new Promise((resolve) => { server = app.listen(0, resolve); });
    baseUrl = `http://127.0.0.1:${server.address().port}`;
  });

  after(async () => {
    if (server) await new Promise((resolve) => server.close(resolve));
    await cleanup();
    mock.restoreAll();
  });

  // ── The four existing fields still arrive ──────────────────────────────────

  it('returns greeting ALONGSIDE the four existing fields', async () => {
    const { status, json } = await callStart(T.CLINIC, '+919000010001');
    assert.equal(status, 200);
    // The contract the worker already depends on must be intact, not replaced.
    for (const field of ['call_session_id', 'customer_id', 'conversation_id']) {
      assert.ok(json[field], `${field} must still be returned`);
    }
    assert.ok('correlation_id' in json, 'correlation_id must still be returned');
    assert.equal(typeof json.greeting, 'string', 'greeting is always a string');
  });

  // ── Per-language greeting, in the namespace the worker actually stores ─────

  for (const [stored, lang] of [['te-IN', 'te'], ['hi-IN', 'hi'], ['en-IN', 'en']]) {
    it(`a caller stored as '${stored}' is greeted in ${lang} — greeting AND consent`, async () => {
      const phone = `+91900002${lang.charCodeAt(0)}${lang.charCodeAt(1)}`;
      await seedCaller(T.CLINIC, phone, stored);
      const { status, json } = await callStart(T.CLINIC, phone);

      assert.equal(status, 200);
      assert.ok(json.greeting.includes(GREET[lang]),
        `expected the ${lang} greeting, got: ${json.greeting}`);
      // The legal-floor line, asserted as its exact configured text.
      assert.ok(json.greeting.includes(CONSENT[lang]),
        `expected the ${lang} recording_consent line, got: ${json.greeting}`);
      // Order: greeting first, then consent — the order the prompt used to impose.
      assert.ok(json.greeting.indexOf(GREET[lang]) < json.greeting.indexOf(CONSENT[lang]),
        'the consent line must follow the greeting');
      // And nothing from another language leaked in.
      for (const other of ['te', 'hi', 'en'].filter((l) => l !== lang)) {
        assert.ok(!json.greeting.includes(GREET[other]), `${other} greeting must not appear`);
        assert.ok(!json.greeting.includes(CONSENT[other]), `${other} consent must not appear`);
      }
    });
  }

  it("THE BUG: 'te-IN' gets Telugu, not the English fallback", async () => {
    // This is the whole point of configLang and the test that dies if it is
    // reduced to the identity: without normalisation `config.greeting['te-IN']`
    // is undefined, pickLine falls back to `en`, and a Telugu clinic's returning
    // Telugu caller is greeted in English by a route that returns 200.
    const phone = '+919000030001';
    await seedCaller(T.CLINIC, phone, 'te-IN');
    const { json } = await callStart(T.CLINIC, phone);

    assert.ok(json.greeting.includes(GREET.te), `expected Telugu, got: ${json.greeting}`);
    assert.ok(!json.greeting.includes(GREET.en), 'must NOT be the English fallback');
    assert.ok(json.greeting.includes(CONSENT.te), 'consent must be Telugu too');
    assert.ok(!json.greeting.includes(CONSENT.en), 'consent must NOT be the English fallback');
  });

  it('the bare config code resolves identically to the BCP-47 one', async () => {
    // Both namespaces, one function: a customer stored 'te' and a customer
    // stored 'te-IN' must be greeted with the same bytes.
    const bare = '+919000040001';
    const tagged = '+919000040002';
    await seedCaller(T.CLINIC, bare, 'te');
    await seedCaller(T.CLINIC, tagged, 'te-IN');

    const a = await callStart(T.CLINIC, bare);
    const b = await callStart(T.CLINIC, tagged);
    assert.equal(a.json.greeting, b.json.greeting);
    assert.ok(a.json.greeting.includes(GREET.te));
  });

  // ── New caller → tenant default ───────────────────────────────────────────

  it('a NEW caller (no stored language) gets the tenant default', async () => {
    // No customer row exists: the greeting must come from
    // config.languages.default, which is the only language knowable before the
    // caller speaks.
    const { json } = await callStart(T.CLINIC, '+919000050001');
    assert.ok(json.greeting.includes(GREET.te), `te is this tenant's default, got: ${json.greeting}`);
    assert.ok(json.greeting.includes(CONSENT.te));
  });

  it("a NEW caller at an en-default tenant gets English — the default is read, not assumed", async () => {
    // Guards the previous test against passing for the wrong reason: if the code
    // hardcoded a language, one of these two must be wrong.
    const { json } = await callStart(T.ENDEF, '+919000060001');
    assert.ok(json.greeting.includes(GREET.en), `en is this tenant's default, got: ${json.greeting}`);
    assert.ok(!json.greeting.includes(GREET.te));
  });

  it('a returning caller OVERRIDES the tenant default', async () => {
    // Same tenant as the previous test (default en), caller stored hi-IN.
    const phone = '+919000070001';
    await seedCaller(T.ENDEF, phone, 'hi-IN');
    const { json } = await callStart(T.ENDEF, phone);
    assert.ok(json.greeting.includes(GREET.hi), `expected Hindi, got: ${json.greeting}`);
    assert.ok(!json.greeting.includes(GREET.en), 'the stored prior must win over the default');
  });

  // ── Unresolvable stored language → default + WARN, never English by accident ─

  it('a garbage stored language falls back to the TENANT DEFAULT and WARNs', async () => {
    const warn = mock.method(logger, 'warn', () => {});
    try {
      const phone = '+919000080001';
      await seedCaller(T.CLINIC, phone, 'xx-ZZ');
      const { json } = await callStart(T.CLINIC, phone);

      // The tenant default is te — NOT English. A normaliser that defaulted to
      // English would pass a weaker version of this test, so assert both sides.
      assert.ok(json.greeting.includes(GREET.te), `expected the te default, got: ${json.greeting}`);
      assert.ok(!json.greeting.includes(GREET.en), 'must not land on English by accident');

      const hit = warn.mock.calls.some((c) => {
        const [obj, msg] = c.arguments;
        return typeof msg === 'string'
          && msg.includes('preferred_language')
          && obj && obj.stored === 'xx-ZZ';
      });
      assert.ok(hit, 'the unresolvable stored value must be WARNed, naming the value');
    } finally {
      warn.mock.restore();
    }
  });

  it('a real but unsupported language (ta-IN) is treated as unresolvable', async () => {
    // Tamil is a language; it is not one this repo serves. Resolving it to
    // anything would be an invention, so it takes the default path.
    const phone = '+919000090001';
    await seedCaller(T.CLINIC, phone, 'ta-IN');
    const { json } = await callStart(T.CLINIC, phone);
    assert.ok(json.greeting.includes(GREET.te));
    assert.ok(!json.greeting.includes(GREET.en));
  });

  // ── Consent gating ────────────────────────────────────────────────────────

  it('consent OFF → the greeting is the greeting alone', async () => {
    const { json } = await callStart(T.NOCONSENT, '+919000100001');
    assert.equal(json.greeting, GREET.te, 'exactly the greeting, no consent line');
    for (const line of Object.values(CONSENT)) {
      assert.ok(!json.greeting.includes(line), 'no consent line in any language');
    }
  });

  it('consent ON → greeting and consent are one spoken string', async () => {
    // One say() call, so they must arrive joined rather than as two fields.
    const { json } = await callStart(T.CLINIC, '+919000110001');
    assert.equal(json.greeting, `${GREET.te} ${CONSENT.te}`);
  });

  // ── Nothing to say ────────────────────────────────────────────────────────

  it('a tenant with NO config row returns an empty greeting, not an error', async () => {
    // The worker treats '' as "say nothing"; the call must still bridge.
    const { status, json } = await callStart(T.NOCONFIG, '+919000120001');
    assert.equal(status, 200);
    assert.equal(json.greeting, '');
    assert.ok(json.call_session_id, 'the call still bridges');
  });

  // ── The language the greeting is IN (Issue 38) ─────────────────────────────
  //
  // V1c resolved the greeting's language correctly and then told the worker
  // nothing about it. The worker synthesised with `language_prior or
  // DEFAULT_LANGUAGE` — a dev-room metadata hint or an env default — so a Telugu
  // greeting could be, and was, spoken by an English voice.
  //
  // The field is emitted in the SPEAKABLE namespace ('te-IN'): the same form the
  // SSE `done` event already sends (internalVoice.js:510) and the form Sarvam
  // TTS's target_language_code takes. That is the point — not a second
  // convention, and no mapping table on the Python side.
  //
  // Every assertion below pairs the code with the TEXT. A `language` that agreed
  // with itself but not with the bytes in `greeting` is the exact bug this
  // closes, so asserting the code alone would be asserting nothing.

  const langOf = (tag) => ({ 'te-IN': 'te', 'hi-IN': 'hi', 'en-IN': 'en' }[tag]);

  function assertGreetingMatchesLanguage(json) {
    const lang = langOf(json.language);
    assert.ok(lang, `language must be a speakable tag, got: ${JSON.stringify(json.language)}`);
    assert.ok(json.greeting.includes(GREET[lang]),
      `language says ${json.language} but the greeting text is not ${lang}: ${json.greeting}`);
    for (const other of ['te', 'hi', 'en'].filter((l) => l !== lang)) {
      assert.ok(!json.greeting.includes(GREET[other]),
        `language says ${json.language} but the ${other} greeting is in the text`);
    }
    return lang;
  }

  it('a te-IN caller: language is te-IN and the text is Telugu', async () => {
    const phone = '+919000380001';
    await seedCaller(T.CLINIC, phone, 'te-IN');
    const { status, json } = await callStart(T.CLINIC, phone);

    assert.equal(status, 200);
    assert.equal(json.language, 'te-IN');
    assert.equal(assertGreetingMatchesLanguage(json), 'te');
    // The consent line rides in the same string and must be the same language.
    assert.ok(json.greeting.includes(CONSENT.te));
  });

  it('a hi-IN caller: language is hi-IN and the text is Hindi', async () => {
    const phone = '+919000380002';
    await seedCaller(T.CLINIC, phone, 'hi-IN');
    const { json } = await callStart(T.CLINIC, phone);

    assert.equal(json.language, 'hi-IN');
    assert.equal(assertGreetingMatchesLanguage(json), 'hi');
    assert.ok(json.greeting.includes(CONSENT.hi));
  });

  it('a tenant-default caller: language is the tenant default, not an env default', async () => {
    // No stored language anywhere — the tenant's own config.languages.default is
    // the only thing that can be known before the caller speaks.
    const { json } = await callStart(T.CLINIC, '+919000380003');
    assert.equal(json.language, 'te-IN', "CLINIC's default is te");
    assert.equal(assertGreetingMatchesLanguage(json), 'te');
  });

  it('a tenant-default caller at an en-default tenant gets en-IN — the default is READ', async () => {
    // The guard against the previous test passing for the wrong reason. A
    // hardcoded 'te-IN' — which is precisely what the worker used to use — makes
    // exactly this one red.
    const { json } = await callStart(T.ENDEF, '+919000380004');
    assert.equal(json.language, 'en-IN', "ENDEF's default is en");
    assert.equal(assertGreetingMatchesLanguage(json), 'en');
  });

  it('a garbage-language caller: language is the TENANT DEFAULT, per V1c', async () => {
    // Consistent with the greeting text's own fallback, which is the property
    // that matters: an unresolvable stored value must not split the two apart and
    // have the worker synthesise Telugu text with an English voice.
    const warn = mock.method(logger, 'warn', () => {});
    try {
      const phone = '+919000380005';
      await seedCaller(T.CLINIC, phone, 'xx-ZZ');
      const { json } = await callStart(T.CLINIC, phone);

      assert.equal(json.language, 'te-IN', 'the tenant default, not English and not the garbage');
      assert.equal(assertGreetingMatchesLanguage(json), 'te');
    } finally {
      warn.mock.restore();
    }
  });

  it('a real-but-unsupported language (ta-IN) takes the same default path', async () => {
    const phone = '+919000380006';
    await seedCaller(T.CLINIC, phone, 'ta-IN');
    const { json } = await callStart(T.CLINIC, phone);
    assert.equal(json.language, 'te-IN');
    assert.notEqual(json.language, 'ta-IN', 'never echo a language the clinic cannot speak');
    assert.equal(assertGreetingMatchesLanguage(json), 'te');
  });

  it('the tag is exactly what the SSE done event emits — one namespace, not two', async () => {
    // The convention this field must match, asserted against the shape rather
    // than against a hand-copied literal: worker-namespace tags, which is what
    // customerService.resolveLanguage returns to `done` and what Sarvam takes.
    const phone = '+919000380007';
    await seedCaller(T.CLINIC, phone, 'hi-IN');
    const { json } = await callStart(T.CLINIC, phone);

    assert.match(json.language, /^[a-z]{2}-[A-Z]{2}$/, 'BCP-47, not a bare config code');
    assert.notEqual(json.language, 'hi', 'the bare config code must NOT leak to the worker');
    assert.equal(json.language, 'hi-IN');
  });

  it('nothing to say → language is null, and the worker keeps its own default', async () => {
    // Null rather than a guess: the worker falls back to its room prior / env
    // default exactly as it did before this field existed. A tag here would tell
    // the worker to synthesise in a language nothing resolved.
    const { status, json } = await callStart(T.NOCONFIG, '+919000380008');
    assert.equal(status, 200);
    assert.equal(json.greeting, '');
    assert.equal(json.language, null);
  });

  it('language accompanies the greeting on every 200 — the worker can always read it', async () => {
    // The field must be present (even as null), not conditionally absent: an
    // absent key and a null both mean "no language", but only one of them is a
    // contract the worker can rely on.
    for (const [tenant, phone] of [[T.CLINIC, '+919000380009'], [T.NOCONFIG, '+919000380010']]) {
      const { json } = await callStart(tenant, phone);
      assert.ok('language' in json, 'language must always be present');
      assert.ok('greeting' in json, 'greeting must always be present');
    }
  });
});
