'use strict';

// GREEN USED TO MEAN `# fail 0`, AND THAT WAS NOT ENOUGH — RAG Session 3 §6.2.
//
// `npm run os:check` is the provenance gate: it re-runs the suite and refuses if
// state.md no longer describes HEAD. It read exactly one counter, `# fail`, and
// `# fail` counts ONE of the three ways a test can end without passing. The other
// two are the ones a broken run actually produces, and this repository has met
// both:
//
//   • CANCELLED. Session 2 hit it for real — an unbounded embedding call drained
//     the event loop and the run reported `# cancelled 4, # fail 0`. A gate
//     reading only `# fail` calls that green.
//   • SKIPPED. `ok N - name # SKIP` is never counted by `# fail` either, and it
//     still counts toward `# tests`, so even the recorded total cannot see it.
//
// Every fixture below is REAL node:test output, generated by spawning the runner
// at test time rather than pasted in as a frozen string. That matters: the gate
// parses the TAP reporter's YAML blocks and `failureType` values, which are node's
// to change. A frozen fixture would keep passing across a node upgrade that had
// already broken the gate in production.
//
// TWO ASYMMETRIES ARE PINNED HERE BECAUSE NEITHER IS GUESSABLE, and both were
// found by measurement rather than from the docs:
//   (a) a throwing `before` hook produces `# fail 0` with `# cancelled N` — the
//       failure is invisible to the old gate entirely;
//   (b) a skipped SUITE (`describe(name, { skip })` — the shape every DB-dependent
//       suite here uses when DATABASE_URL is unset) does NOT increment
//       `# skipped`. Its children are not reported at all, so they vanish from
//       `# tests`. Only the recorded-total comparison catches that one, which is
//       why the totals check has to stay even though it looks redundant.

process.env.LOG_LEVEL = 'silent';

const { describe, it, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const gate = require('../../scripts/os-check.js');

// The fixture sources. Kept as data so generation can happen lazily — see below.
const SOURCES = {
  clean: `
    const { describe, it } = require('node:test');
    describe('clean', () => {
      it('one', () => {});
      it('two', () => {});
    });
  `,
  // One of each condition, no hooks, so they stay independent: a real failure,
  // a real per-test timeout (→ cancelled), a skipped test, and a skipped suite
  // whose children never appear at all.
  mixed: `
    const { describe, it } = require('node:test');
    const assert = require('node:assert/strict');
    describe('mixed', () => {
      it('a genuine failure', () => { assert.equal(1, 2); });
      it('a test that outruns its timeout', { timeout: 20 }, async () => {
        await new Promise((r) => setTimeout(r, 400));
      });
      it('a skipped test', { skip: 'no reason given' }, () => {});
    });
    describe('a skipped suite', { skip: 'DATABASE_URL not set' }, () => {
      it('child one', () => {});
      it('child two', () => {});
    });
  `,
  // (a) above: the hook throws, both siblings are cancelledByParent, and the
  // run reports zero failures.
  hook: `
    const { describe, it, before } = require('node:test');
    describe('a suite whose before hook throws', () => {
      before(() => { throw new Error('genesis failed'); });
      it('sibling one', () => {});
      it('sibling two', () => {});
    });
  `,
};

let tmp = null;
const cache = new Map();

/**
 * Run node:test over one fixture file and hand back its raw TAP.
 *
 * MEMOIZED AND LAZY, DELIBERATELY, and the reason is this session's own subject.
 * Generated from a `before` hook, a spawn that fails cancels every sibling — the
 * run reports `# fail 0, # cancelled 6` and lands in exactly the blind spot §6.2
 * exists to close. (Observed, not theorised: the first draft of this file did it,
 * because the child inherited NODE_TEST_CONTEXT and node refused to run.) Called
 * from inside each test, the same failure is a plain assertion in `# fail`.
 */
function tapFor(name) {
  if (cache.has(name)) return cache.get(name);
  if (!tmp) tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'zyon-oscheck-'));
  const file = path.join(tmp, `${name}.test.js`);
  fs.writeFileSync(file, SOURCES[name]);

  // NODE_TEST_CONTEXT must be stripped: with it set, the child believes it is
  // already inside a test run and skips running files entirely ("run() is being
  // called recursively within a test file"), producing no TAP at all.
  const env = { ...process.env };
  delete env.NODE_TEST_CONTEXT;
  delete env.NODE_OPTIONS;

  const run = spawnSync(process.execPath, ['--test', '--test-reporter=tap', file], {
    encoding: 'utf8', cwd: tmp, env,
  });
  const out = run.stdout || '';
  assert.match(out, /^# tests \d+$/m,
    `fixture ${name} produced no TAP summary:\n${out}\n${run.stderr}`);
  cache.set(name, out);
  return out;
}

const totals = (tap) => ({
  tests: (tap.match(/^# tests (\d+)$/m) || [])[1],
  suites: (tap.match(/^# suites (\d+)$/m) || [])[1],
});

describe('the completion gate refuses on cancelled and skipped, not only on failed', () => {
  after(() => { if (tmp) { try { fs.rmSync(tmp, { recursive: true, force: true }); } catch (_) {} } });

  // ── The control ─────────────────────────────────────────────────────────────
  it('(1) a clean run with matching totals passes', () => {
    assert.deepEqual(gate.suiteGate(tapFor('clean'), totals(tapFor('clean'))), [],
      'a green run must stay green — a gate that cries wolf gets deleted');
  });

  // ── The Session 2 case: cancelled, with `# fail 0` ──────────────────────────
  it('(2) a throwing `before` hook is caught, even though `# fail` is 0', () => {
    const HOOK = tapFor('hook');
    assert.match(HOOK, /^# fail 0$/m,
      'precondition: node really does report zero failures here. If this ever ' +
      'changes, the hole this gate exists to close has closed itself.');
    assert.match(HOOK, /^# cancelled 2$/m, 'precondition: both siblings are cancelled');

    const fails = gate.suiteGate(HOOK, totals(HOOK));
    const cancelled = fails.find((f) => /CANCELLED/.test(f));
    assert.ok(cancelled, `the gate must refuse this run, got: ${JSON.stringify(fails)}`);

    // Named, not counted — the whole reason the failure names were added.
    assert.match(cancelled, /sibling one/);
    assert.match(cancelled, /sibling two/);
    assert.match(cancelled, /cancelledByParent/,
      'the reason a test was cancelled is the first thing the next session needs');
  });

  // ── Failed + cancelled + skipped in one run, each reported on its own terms ──
  it('(3) failure, timeout-cancellation and skip are reported separately and named', () => {
    const MIXED = tapFor('mixed');
    const fails = gate.suiteGate(MIXED, totals(MIXED));

    const red = fails.find((f) => /suite is red/.test(f));
    assert.ok(red, 'the ordinary failure must still be reported');
    assert.match(red, /a genuine failure/);
    assert.doesNotMatch(red, /outruns its timeout/,
      'a cancelled test must NOT be counted among the failures — `# fail` does not ' +
      'count it either, and a list that outranks the number is its own confusion');

    const cancelled = fails.find((f) => /CANCELLED/.test(f));
    assert.ok(cancelled, 'a per-test timeout is a cancellation, and must be refused');
    assert.match(cancelled, /outruns its timeout/);
    assert.match(cancelled, /testTimeoutFailure/);

    const skipped = fails.find((f) => /SKIPPED/.test(f));
    assert.ok(skipped, 'a skipped test must be refused — zero SKIP directives exist at HEAD');
    assert.match(skipped, /a skipped test/);
    assert.match(skipped, /no reason given/, 'the skip reason is reported when node gives one');
  });

  // ── (b) the asymmetry the counter cannot see ────────────────────────────────
  it('(4) a skipped SUITE is named but never counted, so the totals check is what catches it', () => {
    const MIXED = tapFor('mixed');
    assert.match(MIXED, /^# skipped 1$/m,
      'precondition: the skipped SUITE does not increment `# skipped` — only the ' +
      'skipped TEST does. Its two children are not reported at all.');

    const named = gate.skipDirectives(MIXED);
    assert.ok(named.some((s) => s.name === 'a skipped suite' && s.kind === 'suite'),
      `the suite-level directive must still be NAMED: ${JSON.stringify(named)}`);

    // The children vanished from `# tests`, so a run that silently dropped them is
    // invisible to every counter. This is the case the recorded-total comparison
    // exists for, and the reason it is not redundant with the three above.
    const fails = gate.suiteGate(MIXED, { tests: String(Number(totals(MIXED).tests) + 2), suites: totals(MIXED).suites });
    assert.ok(fails.some((f) => /^tests: state\.md says/.test(f)),
      `a run missing two tests must be refused on the total: ${JSON.stringify(fails)}`);
  });

  // ── A counter that cannot be read is not a zero ─────────────────────────────
  it('(5) an unparseable cancelled/skipped counter is a refusal, not a pass', () => {
    const CLEAN = tapFor('clean');
    const stripped = CLEAN.replace(/^# cancelled \d+$/m, '').replace(/^# skipped \d+$/m, '');
    const fails = gate.suiteGate(stripped, totals(CLEAN));
    assert.ok(fails.some((f) => /could not parse `# cancelled/.test(f)),
      'the previous gate was green on conditions it could not see; an unreadable ' +
      'counter is exactly that condition again');
    assert.ok(fails.some((f) => /could not parse `# skipped/.test(f)));
  });

  // ── Rollups are not failures ────────────────────────────────────────────────
  it('(6) a `not ok` SUITE line is not counted as a failing test', () => {
    const MIXED = tapFor('mixed');
    const leaves = gate.notOkLeaves(MIXED);
    assert.ok(leaves.every((l) => l.name !== 'mixed'),
      'the enclosing suite is `not ok` only because a child is; counting it would ' +
      'report one broken test three times over');
    assert.equal(leaves.filter((l) => !l.cancelled).length, 1, 'exactly one real failure');
    assert.equal(leaves.filter((l) => l.cancelled).length, 1, 'exactly one cancellation');
  });
});
